### ISSUE TITLE
Full type signatures for objects

### ISSUE THREAD

**Issue by OJFord** [tjson/tjson-spec#41]
Should e.g. an array of objects contain the complete type of the objects collected at the same level? `A<O<foo:i;bar:f>>` or similar?

Allowing objects of any internal structure seems like a break from homogeneity.

**Comment by tarcieri** [comment]
I've had several people suggest this. One option is to "hoist" all of the type information into the toplevel object, but I think that would make for much larger type signatures which may be annoying. Something to think about, I guess.

Otherwise this information in the serialization is redundant as this information is already carried by the containing object, e.g.:

``` json
{
  "someobject:A<O<foo:i;bar:f>>": [
    {
      "foo:i": "42",
      "bar:f": 42.0
    }
  ]
}
```

Checking for homogenous objects in absence of such a complete type signature is tricky, especially trying to account for things like optional attributes.

In absence of a complete type signature for each object we could specify some rudimentary checking to ensure homogeneity.

**Comment by tarcieri** [comment]
I think a full type specification is probably best handled by an outer envelope (which is something I've discussed with @benlaurie before for other purposes). Strawman:

``` json
{
    "tjson": "draft-2016-11-10",
    "types": {
        "Foobar": "O<foo:i,bar:f>"
    },
    "object": {
        "something:A<Foobar>": [
            {
                "foo:i": "42",
                "bar:f": 42.0
            }
         ]
    }
}
```

**Comment by benlaurie** [comment]
Presumably you could also:

```
{
    "tjson": "draft-2016-11-10",
    "object": {
        "something:A<O<foo:i,bar:f>>": [
            {
                "foo:i": "42",
                "bar:f": 42.0
            }
         ]
    }
}
```

**Comment by benlaurie** [comment]
Doh! I see that's where we came in - but anyway, I think that form should also be permitted.

**Comment by tarcieri** [comment]
Closing this for now: it can be revisited in future versions of the spec
